### ISSUE TITLE
Layout broken on Linux Ubuntu Firefox

### ISSUE THREAD

**Issue by vikkre** [vikkre/hvz#19]
![Screenshot_2020-10-26 HVZ - Bestandsliste 17 53](https://user-images.githubusercontent.com/24613840/97229218-4bfa4600-17d8-11eb-8c1a-8f73a02e8c33.png)

**Comment by ralfkret** [comment]
Hm, das ist ja das alte Frontend....
Das neue Frontend muss gebaut werden. Wie steht in `frontend/readme.md`. Der Output von dem Build liegt in `frontend/dist`. 
`frontend/dist` ist in der nginix config auf `www` gemappt. 

Ich bin gerade dabei den Build in einen Container einzubauen, damit man nicht node installieren muss.
