### ISSUE TITLE
API schema refit to current standart

### ISSUE THREAD

**Issue by vikkre** [vikkre/hvz#36]
The API must be refit to follow the current documented standard.

**Comment by vikkre** [comment]
API ist jetzt auf aktuellem Stand.
Doku ist angepasst.

**Comment by ralfkret** [comment]
Hm, hast Du die Änderungen auch committed? Ich kann keinen Unterschied und auch keinen Commit finden.

**Comment by vikkre** [comment]
https://github.com/vikkre/hvz/commit/680489eb7a1f2be7d2b7174eb2f0af57a8f6f0de ist im branch https://github.com/vikkre/hvz/tree/36-API-schema-refit-to-current-standard drinne
