### ISSUE TITLE
Front end build does not write builddone

### ISSUE THREAD

**Issue by ralfkret** [vikkre/hvz#38]
Der Frontendbuild, der im Container web durchgeführt wird (als multistage build) schreibt nicht die Datei `builddone` auf die der end-to-end-test waretet, bevor er los läuft.
Der Test wird erst gestartet, wenn der Wartevorgang abbricht. Dadurch wird ca. eine oder zwei Minuten verschwendet.

Hier ein Auszug aus dem log:
```
waitfor_frontend_build : Waiting for http://hvz_web/builddone (1 of 20)
...
waitfor_frontend_build : Waiting for http://hvz_web/builddone (19 of 20)
waitfor_frontend_build : Waiting for http://hvz_web/builddone (20 of 20)
waitfor_frontend_build : Wait for http://hvz_web/builddone failed
```

**Comment by ralfkret** [comment]
Eventuell in `package.json` ein Postbuild einbauen, dass die Datei schreibt?
Nee! Das würde bei `npm run watch` nicht funktionieren.

**Comment by vikkre** [comment]
Ich würde einfach sagen, dass der Test-Container auf den Web-Container wartet, wenn der Web-Container ist, dann ist auch der Build fertig. Das ist derzeit auch der Fall. Deshalb kannst man einfach die Überprüfung auf builddone wegnehmen.
